version: "3.5"
services:
    app: 
        environment:
            CHOKIDAR_USEPOLLING: "true"
        volumes: 
            - ./src:/app/src
        container_name: frontend_dnit
        build:
            context: ./
        command: yarn start
        ports:
            - "3000:3000"