name: Push Sonar Metrics
on:
 push:
   branches:
     - main
     - develop
 pull_request:
   types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Print env
        run: printenv
      - name: Install dependencies
        run: npm install
      - name: Test and coverage
        env:
          REACT_APP_API_USUARIOS: https://usuario.dnit.eps-fga.live
          REACT_APP_API_ESCOLAS: https://escola.dnit.eps-fga.live
          REACT_APP_API_UPS: https://up.dnit.eps-fga.live
        run: npm run test:cov -- --silent
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
